name: Issue Assignment

on:
  issues:
    branches: [ "main" ]
    types: [opened]

  pull_request:
    branches: [ "main" ]
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: 'Assign Issue / Pull Request'
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          assignees: ryderbelserion
          numOfAssignee: 1
          allowSelfAssign: false
